// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy4-ghQcUIS8h8XKqapDcQH7ZoDp84vdQ',
    appId: '1:33996350635:web:93ca5f773a7c04e833c3ee',
    messagingSenderId: '33996350635',
    projectId: 'exihibitiondatacollection',
    authDomain: 'exihibitiondatacollection.firebaseapp.com',
    storageBucket: 'exihibitiondatacollection.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbskvLORxoN91YfRLQIJf5TQIzEOjeZbg',
    appId: '1:33996350635:android:65138ad66b7104c333c3ee',
    messagingSenderId: '33996350635',
    projectId: 'exihibitiondatacollection',
    storageBucket: 'exihibitiondatacollection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNpJtOTVVmP3k9f3ngaO6KTtmbGaLB9xQ',
    appId: '1:33996350635:ios:f058f50c061d305c33c3ee',
    messagingSenderId: '33996350635',
    projectId: 'exihibitiondatacollection',
    storageBucket: 'exihibitiondatacollection.appspot.com',
    iosBundleId: 'com.example.exhibitionDataCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNpJtOTVVmP3k9f3ngaO6KTtmbGaLB9xQ',
    appId: '1:33996350635:ios:ed50d94897e189ec33c3ee',
    messagingSenderId: '33996350635',
    projectId: 'exihibitiondatacollection',
    storageBucket: 'exihibitiondatacollection.appspot.com',
    iosBundleId: 'com.example.exhibitionDataCollection.RunnerTests',
  );
}
